services:

  app:
    # Usamos una imagen de Microsoft optimizada para Java y DevContainers
    image: mcr.microsoft.com/devcontainers/java:25-bookworm
#    image: mcr.microsoft.com/devcontainers/java:25
#    image: mcr.microsoft.com/devcontainers/java:1-21-bullseye
    volumes:
#      - ../..:/workspace/${localWorkspaceFolderBasename}:cached
#      - ../..:/workspace/primerSpringBootAzure:cached
#      - ../..:/workspace:cached
      - ../..:/workspace/${localWorkspaceFolderBasename}:cached
    network_mode: bridge
#    network_mode: service:db # Opcional: para compartir red local fácilmente
#    depends_on:
#      - db

#
#  db:
#    image: postgres:18 # O la versión que prefieras
#    restart: unless-stopped
#    environment:
##      POSTGRES_USER: user
#      POSTGRES_USER: myuser
#      POSTGRES_PASSWORD: secret
#      POSTGRES_DB: postgres
#    ports:
#      - "5432:5432"
#    volumes:
#      - db_data:/var/lib/postgresql
#    labels:
#      # Le dice a Spring que inyecte el DataSource automáticamente
#      org.springframework.boot.service-connection: postgres
#      org.springframework.boot.readiness-check.tcp.disable: true
#
#  redis:
#    image: redis:8.2.1
#    ports:
#      - "6379:6379"
#    # Para que Spring le asigne un puerto aleatorio unico:
#    #    ports:
#    #      - "6379"
#    restart: always
#    labels:
#      org.springframework.boot.readiness-check.tcp.disable: true


volumes:
  db_data:
