-- ═══════════════════════════════════════════════════════════════════════════════════════════════
-- V1 — esquema inicial.
--
-- Generado con `make db-baseline` a partir del metadato de las entidades JPA, y despues REVISADO A MANO
-- (los nombres de constraint que pone Hibernate son del tipo `FKbln6r98r68115xdj69n2rdsgn`).
--
-- ⚠️ A PARTIR DE AQUI MANDA FLYWAY. Este fichero NO se regenera ni se edita: cambiar su contenido cambia
-- su checksum y Flyway aborta con "Migration checksum mismatch" alli donde ya estuviera aplicada. Los
-- cambios de esquema van en V2__..., V3__..., escritos a mano.
--
-- Las columnas de auditoria (created_at/by, updated_at/by) y `version` vienen de BaseEntity: las tiene
-- toda entidad del proyecto. Las tablas `*_aud` y `revinfo` las exige Hibernate Envers, por el @Audited.
-- ═══════════════════════════════════════════════════════════════════════════════════════════════

create sequence revinfo_seq start with 1 increment by 50;

create table revinfo (
    rev      integer not null,
    revtstmp bigint,
    primary key (rev)
);

create table my_table (
    id                 bigint generated by default as identity,
    my_table_parent_id bigint unique,
    name               varchar(200),
    surname            varchar(200),
    description        varchar(200),

    -- Auditoria: quien y cuando. `timestamp with time zone` y no `timestamp` a secas: sin zona, el
    -- mismo valor significa cosas distintas segun donde corra el servidor, y eso no se nota hasta que
    -- hay dos regiones o cambia la hora.
    created_at         timestamp(6) with time zone not null,
    created_by         varchar(255),
    updated_at         timestamp(6) with time zone not null,
    updated_by         varchar(255),

    -- Bloqueo optimista. Hibernate la incrementa sola en cada UPDATE.
    version            bigint not null,

    primary key (id)
);

create table my_table_aud (
    rev                integer  not null,
    revtype            smallint,
    id                 bigint   not null,
    my_table_parent_id bigint,
    name               varchar(200),
    surname            varchar(200),
    description        varchar(200),
    primary key (rev, id)
);

alter table my_table
    add constraint fk_my_table_parent
    foreign key (my_table_parent_id) references my_table;

alter table my_table_aud
    add constraint fk_my_table_aud_revinfo
    foreign key (rev) references revinfo;
